# Generated by Django 3.1.7 on 2021-05-03 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210409_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='kon_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Начало'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категория'),
        ),
    ]
